os:
  - linux
  - osx
  - windows
language: rust
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo test --all
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo fmt --all -- --check

before_deploy:
  - cargo doc --no-deps
  - echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2 | tr '-' '_'`/index.html>" > target/doc/index.html

deploy:
  provider: pages
  local_dir: target/doc
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: master
    rust: stable
