language: rust
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo test --all
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo fmt --all -- --check

before_deploy:
  - cargo doc --no-deps

deploy:
  provider: pages
  local_dir: target/doc/dir_assert
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: master
    rust: stable
